<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CMS\CourseController;
use App\Http\Controllers\CMS\TestimonialController;
use App\Http\Controllers\CMS\GalleryController;
use App\Http\Controllers\CMS\EventController;
use App\Http\Controllers\CMS\NoticeController;
use App\Http\Controllers\CMS\BannerController;
use App\Http\Controllers\CMS\PageController;
use App\Http\Controllers\CMS\CollegeMessageController;
use App\Http\Controllers\CMS\MessageController;

Route::get('/admin/dashboard/course/add', [CourseController::class, 'create'])->name('course.add');
Route::get('/admin/dashboard/course/table', [CourseController::class, 'index'])->name('course.table');
Route::post('/admin/dashboard/course/store', [CourseController::class, 'store'])->name('course.store');
Route::get('/admin/dashboard/course/delete/{id}', [CourseController::class, 'destroy'])->name('course.destroy');
Route::get('/admin/dashboard/course/status/{id}', [CourseController::class, 'status'])->name('course.status');
Route::get('/admin/dashboard/course/edit/{id}', [CourseController::class, 'edit'])->name('course.edit');
Route::post('/admin/dashboard/course/edit/update/{id}', [CourseController::class, 'update'])->name('course.update');
Route::get('/admin/dashboard/course/delete/gallery/{id}/{index}', [CourseController::class, 'galleryDelete'])->name('course.gallery.delete');
Route::get('/admin/dashboard/testimonial/add', [TestimonialController::class, 'create'])->name('testimonial.add');
Route::get('/admin/dashboard/testimonial/table', [TestimonialController::class, 'index'])->name('testimonial.table');
Route::post('/admin/dashboard/testimonial/store', [TestimonialController::class, 'store'])->name('testimonial.store');
Route::get('/admin/dashboard/testimonial/delete/{id}', [TestimonialController::class, 'destroy'])->name('testimonial.destroy');
Route::get('/admin/dashboard/testimonial/status/{id}', [TestimonialController::class, 'status'])->name('testimonial.status');
Route::get('/admin/dashboard/testimonial/edit/{id}', [TestimonialController::class, 'edit'])->name('testimonial.edit');
Route::post('/admin/dashboard/testimonial/edit/update/{id}', [TestimonialController::class, 'update'])->name('testimonial.update');
Route::get('/admin/dashboard/gallery/table', [GalleryController::class, 'index'])->name('gallery.table');
Route::post('/admin/dashboard/gallery/store', [GalleryController::class, 'store'])->name('gallery.store');
Route::get('/admin/dashboard/gallery/delete/gallery/{id}/{index}', [GalleryController::class, 'galleryDelete'])->name('gallery.delete');
Route::get('/admin/dashboard/event/add', [EventController::class, 'create'])->name('event.add');
Route::get('/admin/dashboard/event/table', [EventController::class, 'index'])->name('event.table');
Route::post('/admin/dashboard/event/store', [EventController::class, 'store'])->name('event.store');
Route::get('/admin/dashboard/event/delete/{id}', [EventController::class, 'destroy'])->name('event.destroy');
Route::get('/admin/dashboard/event/status/{id}', [EventController::class, 'status'])->name('event.status');
Route::get('/admin/dashboard/event/edit/{id}', [EventController::class, 'edit'])->name('event.edit');
Route::post('/admin/dashboard/event/edit/update/{id}', [EventController::class, 'update'])->name('event.update');
Route::get('/admin/dashboard/event/delete/gallery/{id}/{index}', [EventController::class, 'galleryDelete'])->name('event.gallery.delete');
Route::get('/admin/dashboard/notice/add', [NoticeController::class, 'create'])->name('notice.add');
Route::get('/admin/dashboard/notice/table', [NoticeController::class, 'index'])->name('notice.table');
Route::post('/admin/dashboard/notice/store', [NoticeController::class, 'store'])->name('notice.store');
Route::get('/admin/dashboard/notice/delete/{id}', [NoticeController::class, 'destroy'])->name('notice.destroy');
Route::get('/admin/dashboard/notice/status/{id}', [NoticeController::class, 'status'])->name('notice.status');
Route::get('/admin/dashboard/notice/edit/{id}', [NoticeController::class, 'edit'])->name('notice.edit');
Route::post('/admin/dashboard/notice/edit/update/{id}', [NoticeController::class, 'update'])->name('notice.update');
Route::get('/admin/dashboard/banner/add', [BannerController::class, 'create'])->name('banner.add');
Route::get('/admin/dashboard/banner/table', [BannerController::class, 'index'])->name('banner.table');
Route::post('/admin/dashboard/banner/store', [BannerController::class, 'store'])->name('banner.store');
Route::get('/admin/dashboard/banner/delete/{id}', [BannerController::class, 'destroy'])->name('banner.destroy');
Route::get('/admin/dashboard/banner/status/{id}', [BannerController::class, 'status'])->name('banner.status');
Route::get('/admin/dashboard/banner/edit/{id}', [BannerController::class, 'edit'])->name('banner.edit');
Route::post('/admin/dashboard/banner/edit/update/{id}', [BannerController::class, 'update'])->name('banner.update');
Route::get('/admin/dashboard/page/add', [PageController::class, 'create'])->name('page.add');
Route::get('/admin/dashboard/page/table', [PageController::class, 'index'])->name('page.table');
Route::post('/admin/dashboard/page/store', [PageController::class, 'store'])->name('page.store');
Route::get('/admin/dashboard/page/delete/{id}', [PageController::class, 'destroy'])->name('page.destroy');
Route::get('/admin/dashboard/page/status/{id}', [PageController::class, 'status'])->name('page.status');
Route::get('/admin/dashboard/page/edit/{id}', [PageController::class, 'edit'])->name('page.edit');
Route::post('/admin/dashboard/page/edit/update/{id}', [PageController::class, 'update'])->name('page.update');
Route::get('/admin/dashboard/college-message/add', [CollegeMessageController::class, 'create'])->name('college_message.add');
Route::get('/admin/dashboard/college-message/table', [CollegeMessageController::class, 'index'])->name('college_message.table');
Route::post('/admin/dashboard/college-message/store', [CollegeMessageController::class, 'store'])->name('college_message.store');
Route::get('/admin/dashboard/college-message/delete/{id}', [CollegeMessageController::class, 'destroy'])->name('college_message.destroy');
Route::get('/admin/dashboard/college-message/status/{id}', [CollegeMessageController::class, 'status'])->name('college_message.status');
Route::get('/admin/dashboard/college-message/edit/{id}', [CollegeMessageController::class, 'edit'])->name('college_message.edit');
Route::post('/admin/dashboard/college-message/edit/update/{id}', [CollegeMessageController::class, 'update'])->name('college_message.update');
Route::post('/send/form/data', [MessageController::class, 'store'])->name('message.send');
Route::get('/admin/dashboard/message', [MessageController::class, 'index'])->name('message.index');
Route::get('/admin/dashboard/message/read-toggle/{id}', [MessageController::class, 'toggleRead'])->name('message.toggle-read');
Route::get('/admin/dashboard/message/delete/{id}', [MessageController::class, 'destroy'])->name('message.destroy');
Route::post('/admin/dashboard/message/bulk-delete', [MessageController::class, 'bulkDestroy'])->name('message.bulk-destroy');
